config/routes.rb
Rails.application.routes.draw do

  resources :posts
  root 'posts#index'
  
end

app/models/post.rb
class Post < ActiveRecord::Base

  def self.all_post_titles
    posts = Post.all

    display_titles = []
    posts.each do |p|
      display_titles << "#{p.title}"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new
    post.title = params[:post][:title]
    post.body = params[:post][:body]
    if post.save
      flash[:notice] = "Your post was created!"
    else
      flash[:alert] = "Sorry, this post was not created."
    end
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      flash[:notice] = "The post was deleted."
    else
      flash[:alert] = "This post cannot be deleted."
    end
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= flash[:notice] if flash[:notice] %>
  <%= flash[:alert] if flash[:alert] %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div>
	<h1>Posts</h1>
</div>
<% @posts.each do |post| %>
	<div><a href="/posts/<%= post.id %>"><h2><%= post.title %></h2></a></div>
<% end %>
<br>
<div>
  <%= link_to("Create a New Post", new_post_path) %>
</div>

app/views/posts/new.html.erb
<div>
  <h2>
    Create a Post
  </h2>
  <%= form_for @post do |p| %>
    <div>
      <%= p.label :title %>
      <%= p.text_field :title %>
    </div>
    <div>
      <%= p.label :body %>
      <%= p.text_area :body %>
    </div>
    <div>
      <%= p.submit :create %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div>
	<h1><%= @post.title %></h1>
</div>
<div>
	<em>Created <%= @post.created_at %></em>
</div>
<div>
	<p>
		<%= @post.body %>
	</p>
</div>
</br>
<div>
  <%= link_to("Delete This Post", post_path(@post.id), method: :delete) %>
</div>
<br>
<div>
  <%= link_to("Back to List of Posts", posts_path) %>
</div>